### ISSUE TITLE
fill in metadata for data packages

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl-zenodo-storage#4]
See issue catalyst-cooperative/pudl#683 for details.

**Comment by zaneselvans** [comment]
## Zenodo Deposition Metadata
* **`title`**: PUDL Raw {agency} {long form name}
  * PUDL Raw EIA Form 860
  * PUDL Raw EIA Form 861
  * PUDL Raw EIA Form 923
  * PUDL Raw FERC Form 1
  * PUDL Raw EPA IPM/NEEDS
  * PUDL Raw EPA CEMS Hourly
  * PUDL Raw FERC Form 714
  * PUDL Raw Census DP1 Tract
* **`version`**: assume each release requires a major version bump (e.g. 1.0.0 to 2.0.0), since we have no intention of ensuring compatibility between them, which I think you said is the current default behavior.
* **`creators`**:
```
[
    {"name": "Gosnell, Christina", "affiliation": "Catalyst Cooperative"},
    {"name": "Selvans, Zane", "affiliation": "Catalyst Cooperative", "orcid": "0000-0002-9961-7208"}
]
```
* **`description`**: In addition to the dataset specific description that already exists, including the URL for the original download source:
This archive contains raw input data for the Public Utility Data Liberation (PUDL) software developed by Catalyst Cooperative. It is organized into programmatically usable Frictionless Data Packages. For additional information on how to use this data see:
  * https://catalyst.coop
  * https://zenodo.org/communities/catalyst-cooperative/ 
  * https://readthedocs.org/projects/catalystcoop-pudl/ 
  * https://github.com/catalyst-cooperative/pudl
  * https://specs.frictionlessdata.io/data-package/ 
* Note that because of FERC's website reorganization, this URL is no longer valid: https://www.ferc.gov/docs-filing/forms/form-1/data.asp and it should be replaced with: https://www.ferc.gov/industries-data/electric/general-information/electric-industry-forms/form-1-electric-utility-annual in both the Zenodo deposition and datapackage metadata.

## Datapackage Metadata
* The datapackage name field currently doesn’t conform to the datapackage standard, so validation of the datapackage descriptors fails. It must match the regex `'^([-a-z0-9._/])+$'`. The convention we’ve adopted in released, processed datapackages is `pudl-{source1}-{source2}...` with the source codes listed in alphabetical order. Here please use `pudl-raw-{source}` i.e.:
  * `pudl-raw-eia860`
  * `pudl-raw-eia861`
  * `pudl-raw-eia923`
  * `pudl-raw-ferc1`
  * `pudl-raw-epaipm`
  * `pudl-raw-epacems`
  * `pudl-raw-ferc714`
  * `pudl-raw-censusdp1tract`
* **`title`**: Should match the title field of the Zenodo archive.
* Rather than outputting the entire `datapackage.json` on a single line, please pretty-print it so it's both human and machine readable. I think this functionality is built into Python's JSON library.
